### ISSUE TITLE
Error de validación en la pregunta repetir trivia

### ISSUE THREAD

**Issue by julcavasquez** [rhoguevara/TRIVIA_ROGELIO#2]
### **Problema**
La variable repetir_trivia en la línea 206 acepta cualquier valor, según la pregunta solo se debe ingresar los valores S o N.
  #Pregunta de intentos:
` repetir_trivia = input('\n' + MAGENTA + "¿Deseas intentar la trivia nuevamente? [S/N]: " + RESET).upper()`

### Posible Solución
-Validar con un while para que solo acepte los valores S/N.

**Comment by rhoguevara** [comment]
Problema resuelto. Ahora se valida solo con valores de S/N.
