### ISSUE TITLE
Disminuir tiempo del time.sleep

### ISSUE THREAD

**Issue by julcavasquez** [rhoguevara/TRIVIA_ROGELIO#4]
### Sugerencia
Disminuir el time.sleep que se genera antes de mostrar el mensaje de continuar con la siguiente pregunta, para que no de la impresión de que el programa se colgó.
`   time.sleep(5)
    #Refrescar la pantalla:
    input('\n' + "==> Presiona" + RED + " ENTER " + RESET + "para continuar con la 2° pregunta...")
    os.system("clear")`

**Comment by rhoguevara** [comment]
Le puse ese tiempo para que mientras se termine de leer todo lo anterior emerja recien el boton ENTER para continuar. Es cuestion de estetica de cada programador.

**Comment by rhoguevara** [comment]
Le puse ese tiempo para que mientras se termine de leer todo lo anterior emerja recien el boton ENTER para continuar. Es cuestion de estetica de cada programador.
